### ISSUE TITLE
is the id needed?

### ISSUE THREAD

**Issue by rimmesbe** [pinarwastaken/prj-rev-bwfs-dasmoto#2]
I don't really think the h2 needs an id. You can target the h2 uniquely via the section div:
#brushes h2 { ... }
Cleans the html up. Only use id's where you really need it to be an id.

https://github.com/pinarwastaken/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/index.html#L12

**Comment by pinarwastaken** [comment]
I closed this before I fully read it. Just to clarify: I could leave the id out of the h2 and get the same effect needed through the div section. But, since I have class in div (not id), wouldn't it then be: .brushes h2 {...} ?

**Comment by rimmesbe** [comment]
yes

**Comment by pinarwastaken** [comment]
Great! Thanks for the quick response :)
