### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [pinarwastaken/prj-rev-bwfs-dasmoto#6]
Grade: Satisfactory

Summary: Nice job on this project, the end result looks good. Your code was very organized, and you used a lot of good techniques. I created some issues that could be used to slightly improve your code. Small tweaks in organization and efficiency will become very important as projects grow in size. Here a little css cheatsheet that can be a good reference for alternative selectors:
https://adam-marsden.co.uk/css-cheat-sheet/

**Comment by pinarwastaken** [comment]
Thanks for all the tips and the cheat sheet!
